feat: add the workspace-create base functionality
deamgo/uipaas-website pull request #84
Opened 2023-12-18 08:59 UTC by RedCrazyGhost

### Description

add the workspace-create base functionality

Fixes # (issue numbers)

### Checklist

- [ ] I have explained the need for this PR and the problem it solves
- [X] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible

2023-12-18 09:13 UTC, ZhaoKang0610 reviewed
No big problem, it would be better to use validate

2023-12-18 09:14 UTC, zccabb reviewed
add test.

2023-12-18 09:16 UTC, yuluo-yx approved these changes
Plsa adjust code by comment.

2023-12-19 03:32 UTC, zccabb approved these changes

2023-12-19 03:35 UTC, RedCrazyGhost commented on apps/workbench/backend/service/workspace/workspace.go
> +func hashTop6(str string) string {
I think this method of drawing out is necessary

2023-12-19 03:54 UTC, yuluo-yx requested changes

2023-12-19 03:54 UTC, yuluo-yx commented on apps/workbench/backend/api/workspace/workspace.go
> +	"github.com/deamgo/workbench/service/workspace"
add blank line.

2023-12-19 03:54 UTC, yuluo-yx commented on apps/workbench/backend/cmd/main.go
>  	"github.com/gin-gonic/gin"
adjust the order pkg.

2023-12-19 03:54 UTC, yuluo-yx commented on apps/workbench/backend/db/sql/developer_workspace.sql
> +   `developer_id` bigint not null comment '开发者ID',
pls change to en comment.

2023-12-19 03:54 UTC, yuluo-yx commented on apps/workbench/backend/router/router.go
> +	"github.com/deamgo/workbench/api/workspace"
adjust the order pkg

2023-12-19 03:54 UTC, yuluo-yx commented on apps/workbench/backend/service/workspace/workspace.go
> +func hashTop6(str string) string {
> I think this method of drawing out is necessary

okay.

2023-12-19 03:54 UTC, yuluo-yx commented on apps/workbench/backend/service/workspace/workspace_test.go
> +	"context"
Same as above

2023-12-19 08:43 UTC, yuluo-yx approved these changes
LGTM.

2023-12-19 10:13 UTC, merged